The state Supreme Court Appellate Division ordered the Daillo trial moved from the Bronx to Albany, citing prejudicial publicity which would make a fair trial in the Bronx impossible.
The ruling was denounced by prosecutors, Diallo's family, and public figures such as Rev. All Sharpton and Winnie Madikizela-Mandela, and hailed by the Patrolmen's Benevolent Association.
The defendants might still opt for a bench trial rather than jury trial.
Defense attorneys claim the officers fired on Diallo because they mistakenly believed he had a gun and was firing on them.
They had been searching the area for a rape suspect.
