A 7.0 undersea earthquake, followed by a second 5.7 quake, triggered the Papua New Guinea tsunami.
Up to seven villages were destroyed.
Relief supplies are arriving.
However, the area's remoteness has hampered rescue and relief efforts.
With 705 confirmed dead, the final toll could reach around 3,000, most of which are likely children and the elderly.
About 2,500 survivors have been found, and 5,000 remain missing.
Decaying bodies are posing a health threat.
New Zealand and France have offered aid.
The U.S. Secretary of State will visit on July 29 to offer aid in addition financial assistance already offered.
