The grand jury investigating the murder of JonBenet Ramsey continued into September 1999.
Its term expires in October and it can indict, issue a report, or simply adjourn.
In addition to her family, an intruder could be the perpetrator based on some evidence including an unidentified footprint and unidentified DNA.
By July, $1.74 million had been spent on the investigation.
Controversy continues to surround the case.
Investigators have resigned, books are being written, and leaks continue.
A writer was indicted for attempted blackmail and an investigative service is charged with racketeering, after illegally collecting personal data and investigation details.
