There still have been no cases of H5N1 virus outside Hong Kong, where the total is now 13 confirmed cases and six suspected.
Nevertheless, Macao is prepared for a possible outbreak.
Preliminary tests indicate that the virus is transmitted from bird to human.
Hong Kong has slaughtered all poultry on farms and in markets followed by a massive cleaning in an effort to get rid of the source of the flu.
The government plans to adopt confidence-building measures and stricter controls before the raising and sale of chickens is resumed.
Beijing has has offered its assistance.
