Authorities in Hong Kong, Macao, and mainland China increased surveillance and testing in the poultry industry to determine presence of the bird flu virus.
So far the only cases of the virus were in Hong Kong with 13 confirmed and 6 suspected cases, including one involving person to person transmission.
Widespread antibody testing for the H5N1 virus was conducted in Hong Kong with assistance from WHO and CDC.
More than 1 million poultry were slaughtered in Hong Kong; sales of chickens were down 50%.
Recognizing the financial impact, Chinese authorities promised financial assistance to those in need.
