H5N1 found at a local chicken farm and sudden chicken deaths in a market led to the mass slaughter of all chickens in Hong Kong, followed by a thorough cleansing exercise at meat stalls, health checks for poultry workers, and augmentation of out-patient services.
Chicken exports from the mainland are suspended until better health tests are established.
In nearby Macao, officials are increasing inspection of imported and local poultry, and promoting cleaner bird markets.
Farmers must report any dead chickens.
The hospital is preparing medicines and coordination strategies.
Experts suggest eating cooked poultry is safe since cooking destroys the virus.
