Although the world is becoming more aware of the importance of rainforest conservation we have lost far more forest than has been conserved.
A living forest is worth more than a dead one.
Healthy forests prevent erosion and water pollution and help cleanse the air.
Maintaining the forests requires the collaboration of environmentalists and entrepreneurs.
Especially when the forest is in a poor nation, eco-tourism and bio-prospecting can provide income and jobs.
Some wealthier nations have not lived up to their own responsibilities, and the task of saving the forests has fallen on private conservation groups with limited resources.
