US citizens are vulnerable to identity theft because our basic identity documents are easily forged and the government has allowed use of Social Security Numbers as identification numbers.
The crime is becoming more complex as identity theft rings open utility accounts, rent apartments, apply for loans, buy cars, set up businesses, and declare bankruptcy using stolen information.
The FTC has pressured large data collection firms to self-regulate consumer privacy policy to avoid restrictive legislation.
It now offers a toll-free identity theft help line.
Senators and congressmen are submitting proposals to study and remedy issues of consumer privacy, including identity theft.
