Obesity is a serious health problem in the U.S. where one-fourth of the population is obese.
It is the second leading cause of preventable death after smoking.
Treating obesity-related diseases costs $52 billion annually.
American culture emphasizes quantity and the food industry encourages overeating.
We do not exercise.
We are besieged by ads for junk food and one-fourth of the vegetables we eat are French fries.
And it is not just Americans.
Obesity is increasing throughout the world because of Western-style diets and less physical activity.
Even some Japanese police officers are too heavy.
