Obesity is a chronic disease requiring regular medical treatment and a commitment by patients to control their weight.
It is caused by a complicated interaction of genetic and environmental factors.
About 33-50% of the U.S. population is overweight and obesity is the second-leading cause of preventable death, causing an increase in diseases that were heretofore on the decline.
Diet drugs are being developed but concerns are about side effects.
Many advertised weight-loss strategies can have risks and are largely unregulated.
Specialists suggest rewarding proper diet with lower insurance premiums or vacation time.
Family support is essential for weight-loss programs.
