Identity fraud grows as technology advances and criminal use of stolen identities expands to include violent crimes.
Virtually no one is immune.
Laws and enforcement efforts exist but activists contend they do little to stop the problems.
Problems include unregulated information brokers, and no laws against disclosure of private financial information or against buying or selling social security numbers (SSNs).
The Administration has urged businesses to self-regulate.
Congress is drafting legislation to restrict sale and display of SSNs on public documents, restrict credit bureaus from selling SSNs and other personal information and meet other privacy protection requirements.
