Listeria recalls continued with 26 in 1999.
The death toll to an earlier one was raised to 15 and the company was cited for unclean practices and faulty procedures.
Bologna and gourmet foods were also recalled.
Two beef recalls for E. coli occurred in June 2000.
Irradiation was suggested as a preventative, but not all agree.
Other 2000 recalls include taco shells for containing bioengineered corn, a possible allergen; steak products for containing buttermilk and whey, allergens not listed on the label; and beef slated for school lunch programs because the meatpacker failed to meet USDA quality standards.
