In January 1998, prosecutors agreed to recognize Unibomber Theodore Kaczynski's mental illness and allow him to avoid the death penalty with an unconditional guilty plea.
Kaczynski had agreed to psychiatric tests to prove his mental competence after apparently attempting suicide.
The judge rejected his request to dismiss his lawyers and act in his own defense.
With no right of appeal, Kaczynski was sentenced to four life terms without the possibility of parole and cannot profit from his crimes.
His brother David, who turned him in, would give the $1 million reward from the Justice Department to families of the victims.
