Marion County prosecutors dropped the charges against Deborah Lafave after they concluded that the victim's emotional state was more important than a prison sentence for Lafave.
This means the previously agreed-upon deal will stand.
The Marion County judge who had balked at the deal had been criticized by that county's prosecutor for factual errors in his rejection of the plea.
He also was presented with psychiatric opinions concerning damage to the victim's emotional state that a trial could cause.
If convicted in Marion County Lafave could have faced even more prison time than she would have had in Hillsborough County.
