The U.S. Fish and Wildlife Service reports $7.7 million spent protecting the grizzly bear in 2004.
A group of 269 biologists sent a letter to the Service requesting the grizzly not be lifted from the Endangered Species List.
In Canada, protection of grizzlies may come via an agreement between loggers and conservationists, permitting selective and sustainable tree-cutting in part of Great Bear Rain Forest, a grizzly habitat.
Also in western Canada, commercial grizzly bear hunts led a conservation group to buy exclusive hunting rights to a tract of British Columbian land, where it will focus on eco-tourism vice sport-hunting.
