President Bush infuriated environmental groups by naming the Idaho Governor as the new Secretary of the Interior.
If the grizzly is delisted, the three states that would manage the bears are known to be hostile to the bears and hunting and commercial exploitation would return.
A group of 269 scientists has protested delisting the grizzly.
Meanwhile Canada has announced a 16-million acre natural reserve teeming with grizzlies on the Pacific coast; and the Raincoast Conservation Foundation has acquired one of North America's largest guide outfitters, which will no longer cater to hunters but focus on watching and photographing bears.
