The death toll is up to at least 38 from avalanches in western Austria, and the search for victims is drawing near a close, with one person missing and believed dead.
The avalanches are now considered among the most dangerous in 400 years due to the amount of snow.
Their speed was estimated at nearly 200 kilometers per hour.
Roads leading to Galtuer finally become passable and more than 4000 tourists have now left the resorts.
A month later Galtuer's tourist business still had not recovered.
The spring thaw is also expected to hit the area hard, with serious flooding.
