The plea deal reached by Florida's Hillsborough County prosecutors with former middle school teacher Debra LaFave, who committed sex offenses with a student in two counties, was in jeopardy.
Marion County Judge Stancil wanted to hear more evidence and set a date for trial, leaving LaFave and the victim's mother in tears.
In response, Marion prosecutors then dropped all charges, concluding that the emotional welfare and privacy of the victim was more important than sending LaFave to prison.
Therefore, LaFave will live under the plea deal reached in Hillsborough County of three years house arrest and seven years probation.
