On April 5, Russel Henderson pled guilty to the murder of Matthew Shepard to avoid a trial and possible death sentence.
He was sentenced to two consecutive life terms with no possibility of parole.
Shepard had been left for dead on October 7.
The jury selection had been going slowly, with 47 prospective jurors to be questioned on April 6.
Henderson's girlfriend, who had pled guilty of being an accessory after the fact, is awaiting sentence and McKinney's girlfriend's trial on the same charge will begin in May.
