Mount St. Helens emitted short steam eruptions on November 4 and 5.
The earthquakes stopped almost completely after the November 5 eruption, becoming very small and further apart.
On November 6, scientists downgraded the alert level to a 2 (3 means an event likely within 24 hours) and said an eruption could occur in weeks or not at all.
The magma had deformed the volcano's dome by 20%.
Flights had been diverted from the area.
The gathering of indirect data continues, including seismometers pinpointing the tiny earthquakes and the analysis of dust particles.
Rain dampened the record number of tourists.
