The killer of Dutch filmmaker Theo van Gogh, identified as Mohammed B., will be tried as a terrorist for what appears to be the Netherlands first Islamic terrorist attack.
With a latest arrest, eight suspects now remain in police custody.
Dutch Parliament member Ayan Hirsi Ali, scriptwriter for the van Gogh film that sparked the murder, is receiving death threats and is under police protection.
The government vowed to hit back at Muslim extremism by setting aside extra funds for intelligence services and, if necessary, changing legislation to make it easier to crack down on radical Muslims who use violence.
