Since a year after its adverse side effects first made headlines in 1996, the FDA has attempted to regulate the herbal supplement ephedra.
It's received over 800 reports of adverse effects, including 44 deaths.
Ephedra differs from its chemical cousin methamphetamine by only one atom and is the herbal alternative to the illicit drug Ecstasy.
However, despite reports that even small doses can trigger devastating reactions, industry research maintains it is safe in proper doses.
On February 25, the FDA notified Congress that it is launching a new push to address public safety issues posed by ephedra use.
