Within a week of the Norwegian authorities granting Statoil permission to resume limited oil production, the company admitted its internal problems led to the near-disastrous gas leak last November at its A platform.
Full production permission was given in late January but achieving it will take time said Statoil.
Police began investigating Statoil to determine if there was criminal negligence.
The investigation should be done by late March.
Norwegian safety officials issued a highly critical report on Statoil's failures and ordered improvements in four key areas, including improving management involvement and compliance with controlling documents.
