Although prescribed for asthma, ephedra can cause insomnia, worsen high blood pressure and diabetes, should not be given to children, and is marketed to teens as an Ecstasy alternative.
Imports may be tainted with metals or other drugs and some products contain dangerously high quantities.
Under Congressional pressure the FDA withdrew its planned dosage regulations, but on February 25, 2000 announced hearings, which may result in requiring warning labels.
By April, 273 more incidents were reported.
The National Institute of Health is calling for regulations and even producers are investigating issues.
Harvesting the herb in China is harming the environment.
