International groups have proposed a $404 million effort to preserve frogs and other amphibians, noting that one-third of the known species are threatened globally.
Experts are divided on the cause of the decline, with some saying that the sources are unknown with others asserting that human activity is harming wildlife.
A study published in "Nature" presents compelling evidence that global climate change has favored the fungus that grows on the frog's skin, covering the pores and thus making it impossible for him to absorb water.
Meanwhile 20 new frog species were found on an isolated Indonesian jungle island.
