Prosecutors confirmed seven wiretapping operations covering over 1800 politicians, businessmen, and other prominent figures.
Two former NIS chiefs were charged with involvement because, as successive agency heads, they allegedly ignored then-president Kim's order to cease the activity.
(Prosecutors said Kim was not involved).
A deputy chief was also under investigation but committed suicide.
A TV journalist was indicted for violating privacy laws in revealing some of the taped conversations.
North Korea is blaming all the arrests on the opposition party, instigated by the U.S. Meanwhile, the ambassador and two Samsung executives were cleared of embezzlement and bribery charges.
