The FDA's attempts to regulate Ephedra were beaten down by industry protests, political opposition, and criticism that there was a lack of scientific proof that the substance was unsafe.
The agency will try to find new ways to address safety concerns.
The dietary supplement industry is against any law making prescriptions mandatory.
Amongst the individual states regulations on ephedra vary widely.
One caution is that it not be taken with another stimulant like caffeine, because the effects will be magnified to dangerous levels.
Furthermore, the use of ephedra for energy could mask the real cause of low energy, like diabetes.
