Two former NIS chiefs have been arrested and indicted for overseeing the agency's illegal wiretapping of mobile phone calls of some 1800 influential politicians, businessmen, and journalists.
Both have denied the charges.
North Korea denounced the arrests.
A former deputy chief hanged himself after being questioned.
The journalist who broke the story has been indicted for breaking privacy laws.
Samsung's chief and two other top Samsung executives have been cleared of suspicion.
The patriarch of Samsung has offered $825 million to charity.
Prosecutors have said that former President Kim, winner of the Nobel Peace Prize, was not involved.
