The Coastal Conservation Association is urging that the oyster be granted endangered specie status.
This could end all harvesting of the eastern oyster from Maine to Louisiana, even where harvests, also threatened by hurricanes and red tides, remain acceptable.
Compliance with current law and habitat restoration is important.
Sterile Asian oysters are being tested in Virginia.
Others are urging genetic altering of native oysters.
Their importance in filtering sediment and eating algae, which allows sunlight to nourish sea grasses and remove nitrogen, is critical.
Efforts are hindered by the EPA's poor performance and spending cuts recommended by the Bush administration.
