The Dutch government declared war on Islamic extremism following the murder of Theo van Gogh.
The suspect, identified only as Mohammed B, was charged on November 5 with five counts and will be tried as a terrorist.
Four other suspects were charged with terrorist conspiracy.
A fifth man was arrested and charged with conspiring to kill van Gogh's associate, a liberal politician, and to behead a second politician.
There were also calls for more police protection of politicians and artists, more funding for the secret service, and an evaluation of the effectiveness of current laws.
