Two months after a November 2004 natural gas leak halted production on two of Norwegian Statoil's oil platforms in the North Sea, the Norwegian Petroleum Safety Authority (NPSA) approved the company's plan to resume full 205,000 barrel a day production.
Previously, only a partial startup was authorized, pending review of data from that operation.
Statoil's internal investigation acknowledged inadequate planning and a lack of risk appreciation led to the leak.
An investigation by Norwegian state officials in coordination with NPSA for possible criminal negligence revealed 28 failures to meet regulations before the leak, harshly criticized Statoil, and ordered comprehensive improvements.
