China sent two working groups to study the Songhua River pollution and ordered two additional reservoirs to release water.
The concentration of pollutants continues to fall and there have been no cases of poisoning; however, rural residents never got any bottled water and continue to rely on well water.
The river is moving slowly because this is the dry, frozen season.
The pollution is expected to reach Russia by early December.
The Russian Ambassador commented that China should have informed Russia about the spill earlier.
China issued a rare apology to the Russians for any harm and offered its assistance.
