The death toll from the Asian earthquake and tsunami has risen to nearly 280,000, with 115,000 in Indonesia.
Thousands more are still missing.
About 5 million have been made homeless in the affected regions.
Indonesia's GDP could also be affected; that country has USD 4.5 billion in damages and losses.
To help, the G7 countries are freezing debts owed by the Asian nations hardest hit by the disaster.
Because Indonesia is one of the world's most graft-ridden nations, officials there announced plans to closely monitor and report disaster funds and how they are being spent.
