In China, a second Sudan I scare occurred in March, when the dye was found in pepper sauce produced by a Heinz subsidiary.
Nine days later Kentucky Fried Chicken (KFC) stopped selling several items also flavored with spices containing Sudan I. The source of the raw materials was traced to Tianyang Food Co. and its manager was arrested on March 28.
Contaminated foods were found in 12 Chinese provinces and municipalities.
China had banned Sudan I imports in February, but strengthened screening processes, checked food establishments, and ordered recalls.
KFC found a new source for spices and Heinz issued recalls.
