The tsunami left over 160,000 people dead, 5 million homeless, and 1.8 million needing food.
And now malaria threatens.
The G7 countries have frozen debt payments for tsunami-damaged countries.
The US navy aircraft carrier, its military aid center, was to leave in early February.
Other countries, including Sweden, Spain, and Portugal, continue to send aid.
Indonesia, with more than 500,000 in refugee camps, almost 115,000 killed, and more bodies found every day, says the tsunami cost US$4.5 billion but did not hurt economic growth.
It will report money received and spent monthly to allay fears of graft.
