The December 26 tsunamis battered coral reefs already in distress.
The reefs suffered first when the tsunami waves hit, breaking off branches.
Then, when the waves swept back to the ocean, the reefs were buried under sludge and debris, threatening to suffocate them.
The Thai government launched a project for volunteer divers to clear the potentially deadly debris from the reefs.
Damage from the December tsunamis could have been significantly reduced if coastal areas had maintained their natural breakwaters, the coral reefs.
To further reef conservation, France launched a three-year initiative to protect coral reefs in the South Pacific.
