Lebanon was in political turmoil following the car-bombing of Hariri, which killed 17 others.
There were massive demonstrations.
The Prime Minister resigned and then was reappointed as caretaker 10 days later.
Many felt the government was not committed to probing the bombing.
Members of parliament called for an investigation asking for support at the Arab summit and from the UN Security Council.
The Security Council dispatched a team of explosives experts and a fact finding mission.
Syria decided to redeploy troops in Lebanon.
On April 20, Hariri's second eldest son assumed the family's political leadership role.
