Three days into the sentencing trial of Pfc.
England, judge Pohl threw out her guilty plea, declared a mistrial, and returned the case to Lt. Gen. Metz, Fort Hood Commander.
What happens next is conjecture.
Reasons for the action were: Pvt.
Graner's testimony that he had ordered some of England's action for training reasons; and England's statement that she didn't think what she did was wrong.
Earlier, Graner was convicted for his role at Abu Ghraib.
The judge said you can plead guilty only if you believe you are and you can't provide evidence that you aren't.
