Reef damage assessment from the December 26, 2004 tsunami is underway.
Healthy reefs are credited with saving the Maldives.
Other places the tsunami broke reefs coming ashore and deposited debris, oil, and chemicals as it receded.
In Thailand, 100's of divers have volunteered to clear reefs in a 4-month campaign, A survey is underway in Andaman and Nicobar.
In other areas, Taiwan was warned by UNESCO that 75% of its reefs are damaged.
Divers and nuclear power plants add to the threat.
France is financing a project in the south Pacific to improve protected marine sites and establish more sites.
