Beijing's food safety office found Sudan I in a pepper sauce produced by the Chinese subsidiary of the US Heinz Company.
Heinz immediately recalled all six products involved.
Sudan I was also found in products made by Coca Cola and Unilever, as well as some Kentucky Fried Chicken foods, in China.
McDonald's in Britain recalled some products.
The red food dye has been found in twelve Chinese provinces and municipalities, including Beijing and Shanghai.
China plans to strengthen its food screening process.
It has arrested the manager of the supplier and started a criminal investigation.
