Multiple challenges, organizations, and viewpoints hamper attempts to reverse decline and improve conditions of the Chesapeake Bay and its tributaries.
Groups call for education, political will, and/or funding.
After Congressional hearings, a GAO report criticized EPA's work to reduce pollution and plan for meeting goals of Chesapeake 2000, despite spending billions.
Research on introducing the Chinese oyster into the bay continues.
The Bay Foundation formed cooperatives between farmers and watermen to educate on agricultural runoff and conservation methods.
Multiple funding streams supported the Corsica river project to demonstrate reducing pollution through improved farming techniques and technology.
