Jury selection to begin January 31.
In December 1999, the New York appeals court moved the trial to Albany, saying it would be impossible for officers to receive a fair trial in the Bronx because of prejudicial publicity. Defense filed with the court saying it might be impossible to seat an impartial jury because of the politically charged atmosphere.
Debate along racial and political lines included observations that the Judge who would have presided in the Bronx was a black female.
Media and public supposition was that the trial could be before a judge rather than a jury .
