Columbine High School won't be reopened until next fall so students started attending Chatfield High School where procedures were set up to deal with student feelings, including "safe" rooms staffed by counselors.
Of the 23 students wounded in the attack, five remain in hospital.
Investigations continued but now there is no belief in a conspiracy.
A 22-year old man was arrested for selling a gun to the Columbine gunmen.
Klebold's girlfriend purchased the other three weapons used in the attack.
President Clinton announced a White House strategy session on youth violence in response to the shootings.
