Parkinson's disease affects over 1% of people over 65.
Although not fatal, its complications are.
A genetic flaw is responsible for 5% of inherited Parkinson's.
Genetic testing could indicate susceptibility.
Deep brain stimulation is an approved therapy to relieve Parkinson's.
Researchers found stem-cell transplants effective in treating monkeys with Parkinson-like symptoms, and hope to apply the method to humans.
Studies show smoking may slightly delay the onset of Parkinson's.
Mere anticipation of a drug sometimes seems helpful.
An experimental drug was discontinued for safety reasons although some patients seemed to benefit from it and were willing to accept the risks.
