Actions to reduce pollution in the bay include a "flush tax" in Maryland to fund sewage plants and a Virginia plan to upgrade water treatment plants.
The Chesapeake Bay Program is trying to raise people's awareness with advertisements that focus on the bay as a source of seafood.
The most difficult problem remains agricultural and urban runoff, washing pollutants into the Bay.
There continues to be tension between farmers and bay people but one innovative program is aimed at creating a friendly, cooperative relationship between the watermen of Smith Island and the farmers in Rockingham County in northwest Virginia.
