A GAO report panned the 10-year Chesapeake Bay clean-up program, citing misleading reports and statistics.
Meanwhile, a new cooperative program is hoped to ease tension between bay people and farmers, who are often blamed for agricultural pollution.
Student activity includes planting foliage buffers to filter runoff.
Crabmeat is highlighted in a Save-the-Bay campaign warning against lawn fertilizer that can wind up in the Chesapeake.
Power plants are targeted for their harmful nitrogen-laden runoff.
A petition to list the oyster as an endangered species is being reviewed but there is strong opposition; such a move could devastate the seafood industry.
