Xinhua reported that Floyd became a Category 5 hurricane on September 13.
The next day it hit the Bahamas with heavy rain, 25-foot seas, and 140 mph winds.
Most tourists had evacuated and residents had moved to safer locations.
Property damage and minor injuries were reported.
Floyd is now expected to hit the U.S. on September 16.
The area of preparations and evacuations has now been extended to southern North Carolina.
President Clinton declared Florida and Georgia disaster areas on September 15, which will facilitate immediate recovery operations if needed.
