Medical evidence supports the theory that Flight 522 suffered cabin decompression that possibly incapacitated both pilots.
Reports suggest they may have failed to respond to a cabin pressure warning.
There are media reports that a switch that controls cabin pressure may have been left in the wrong position after a safely check.
The same aircraft lost cabin pressure in December when a door was not properly sealed.
Another man onboard, probably a flight attendant, attempted to steer the plane just before it crashed.
Ultimately, after having flown for hours on autopilot, the plane crashed when it ran out of fuel.
