In December 1999, the Indonesian Attorney General's office reopened its inquiry into former President Soeharto's allegedly ill-gotten wealth, citing new proof.
The investigation had been stopped in October 1999 for insufficient evidence, a move that triggered anger from many parties nationwide.
Earlier, critics had claimed the government was stalling attempts to determine the source of Soeharto's fortune.
Soeharto has been summoned twice to the AGs office but declined due to health reasons.
If he fails a third summons the Attorney General's office can legally use force to make him appear.
