There is no trace of Natalee Holloway some six weeks after her disappearance.
Suspect Joran van der Sloot's father was arrested on June 23 and held three days on suspicion of having knowledge of, or being involved in the disappearance, and of coaching his son and other suspects on what to tell police.
Joran admitted to lying, and changed his story about the night Natalee vanished.
He now says he was alone with her on the beach, but left her there unharmed.
He remains in jail.
Authorities can hold him until September 4, when he must be charged or released.
