Testing was inconclusive on a possibly infected animal so brain tissue was taken to the foremost lab in England for final tests.
The animal hadn't entered food or feed chain.
This action came shortly after the Administration announced lifting the ban on Canadian cattle.
Law suits ensued and a Federal judge ordered the ban continue.
Some argue that a few diseased animals would not be unsafe because current systems prevent potentially infectious tissue from becoming human or animal food.
A goat in France is infected with BSE, the first case of transmission to another species used for human consumption.
