Six weeks after Natalee Holloway disappeared, only Joran remained incarcerated, the remaining 6 men having been released for lack of evidence, including Joran's father, Paul van der Sloot, who was held for three days.
The Attorney General said the father had counseled his son that without a body there was no case.
Joran can continue to be held until September 4 when he must be charged or released.
A three-judge panel recently ruled there were grounds to continue to hold Joran.
Massive searches by Dutch marines, FBI, Aruba police, and volunteers, have found no physical evidence of murder.
