Massive disruptions of air and sea transportation occurred as thousands of residents and tourists on the 600-mile chain of 700 Bahama islands prepared for Floyd's arrival on Tuesday, September 13.
It arrived with winds of 140 mph.
Downed trees and power lines knocked out phone service so the extent of damages was unknown.
Veering northeast, Floyd was expected to miss a direct hit on Florida and arrive on the Carolina coastal area Thursday.
President Clinton, on travel in New Zealand, issued a disaster declaration for Florida to Georgia to allow recovery efforts to start as soon as the storm ended.
