Joran van der Sloot's father, Paul, was arrested on June 23, apparently for coaching his son after Holloway's disappearance.
On June 26, the release of Paul and the disc jockey was ordered.
On July 4, the release of the Kalpoes brothers also was ordered.
Joran remained in custody through July 16 and can be held until September 4.
The search for Holloway continued unsuccessfully and involved a Texas rescue group, FBI, Dutch Marines, police, islanders, and tourists.
An Aruba official said there was no evidence to support a murder charge and as of July 16 no charges have been issued.
