Obesity is a chronic disease and likely to become the preeminent public health problem.
In October 1998, 55% of Americans were obese or overweight.
Obesity can cause skeletal problems and some forms of cancer, and prevents Japanese police from doing their job.
Causes include hormone irregularities and genetics, but also too much junk food and television.
Scientists are studying leptin, the hormone produced by fat cells.
Obesity treatments include weight loss programs, diet drugs, and walking 10,000 steps a day.
