In November 1998, Indonesian legislators demanded speedier investigation of former President Soeharto's wealth.
Several months later, Time magazine reported that Soeharto had $9 million in an Austrian bank.
The Attorney General was directed to obtain proof of these allegations.
Five months later, he stopped the Soeharto investigation citing lack of evidence.
Within three months, a new Attorney General said Soeharto was a suspect and summoned him to appear.
Soeharto did not appear, due to poor health.
The Attorney General said he would be summoned twice more and could then be brought in by force.
