In May 1999 Time Magazine reported that the Soeharto family amassed 15 billion dollars in cash during his rule, including 9 million that was transferred from a Swiss bank to an Austrian one.
Soeharto claims that he has no money in foreign banks, but does have money and property in Indonesia.
Soeharto has been accused of criminal activity and corruption in a national car project, as well as in nine charities he chaired.
The Indonesian Attorney General has summoned Soeharto to his office twice, but Soeharto has not appeared, claiming ill health from a stroke the previous year.
