The Monday January 6 trial of the Unabomber was delayed when Kaczynski complained about his lawyers.
The judge rejected Kaczynski's request to dismiss his attorneys and the trial resumed Thursday.
Two weeks later, he pleaded guilty unconditionally to all Federal charges, giving up any appeal rights.
On May 4, Kaczynski was sentenced to four life terms without the possibility of release and prohibited from any action in which he could profit from his crimes.
Before the trial, prosecutors agreed not to seek the death penalty, recognizing Kaczynski's mental illness, and allow him to plead guilty to all the crimes.
