In January 2006, federal officials unveiled their plan for removing Yellowstone grizzly bears from the endangered species list, while continuing protection in the park and adjacent federal lands.
If the approximately 600 bears dropped below 500 or if there was a significant loss of habitat, a scientific review would be required.
If threats to the bears were deemed severe, the bears could be re-listed.
During the 30-day public comment period, a group of 269 scientists from around the US asked the Fish and Wildlife Service not to lift the protections.
The Service expects to decide on delisting sometime in 2006.
