The US and China joined countries voicing opposition to Japan's expanded whaling plans and calling for strengthened whale conservation.
At the International Whaling Commission (IWC) meeting in Ulasan, South Korea, Japan hoped to gain support for its proposal to increase so-called scientific whaling and for the eventual repeal of the 19-year commercial whaling ban.
However, on June 22, pro-whaling countries led by Japan failed to muster a majority.
The IWC condemned Japan's proposal and passed an Australian non-binding resolution urging it to either withdraw its proposal or revise it to ensure scientific data is obtained by non-lethal means.
