In an unconditional plea agreement, giving up any right to appeal his case, Kaczynski acknowledged he was the Unabomber and pled guilty to all the federal charges against him.
He was sentenced to four life terms in prison with no chance of release.
He was told he could not profit from his crimes by any means, such as publishing books or giving interviews.
(So far he has contacted a publisher and a documentary producer).
As his trial began he had complained about his lawyer and after a failed suicide attempt he won the right to act on his own behalf.
