On April 5, Russell Henderson pleaded guilty to felony murder and kidnapping charges and was sentenced to two consecutive life terms in prison.
By doing so, he avoided the possibility of the death penalty and saved the small town of Laramie possibly $100,000.
Henderson admitted involvement in Matthew Shepard's murder, but blamed his co-defendant with the beating.
Henderson's girlfriend pleaded guilty to accessory after the fact in December, and McKinney's girlfriend will stand trial on an accessory charge in May.
The President plans to endorse a bill that would expand federal hate-crime laws to include offenses based on sexual orientation.
