As rescuers continued their search, the death toll In the Austrian ski resort of Galtuer continued to rise to 38 as a result of avalanches that struck on consecutive days in late February 1999.
Because of the amount of snow involved and the avalanche speeds of nearly 200 kilometers an hour, these avalanches were considered to be the most dangerous in 400 years.
As the search for survivors continued, Austrian authorities flew thousands out of Galtuer and nearby areas by helicopter.
In March, usually the best month of the year for tourists, hardly anyone had come to Galtuer.
