Many attempts have been made to rebuild the Chesapeake Bay oyster population, from building oyster reefs to establishing sanctuaries.
Maryland has initiated a project on one river to reduce pollution and restore natural habitats as a blueprint for further action.
Some organizations want to have oysters declared an endangered species, which would completely destroy the oyster industry but would give the oysters a chance to recover.
Many people reject the Maryland governor's quick fix of using Asian oysters because they fear unknown consequences.
Meanwhile one innovative waterman provides floating oyster reefs to clean up the bay.
