A controversial 2000 US Air Force report indicates "particularly strong" evidence linking Agent Orange to diabetes in veterans involved in spraying the defoliant.
This report doubtless will lead to increased calls for additional disability payments for veterans and fuel the longstanding scientific debate over the link between Agent Orange and other diseases.
Media reports of secret tests of Agent Orange in Panama during the Vietnam War and the spraying of the defoliant south of the Korean Demilitarized Zone in 1968-1969 were denied by US officials.
The US and Vietnam are expected to conduct joint Agent Orange research in 2000.
