Knowledge is increasing about why the world’s frog population is declining.
In Indonesia, loss of habitat (declining rain forest) is one reason.
Experts are identifying previously unknown frog species while finding an almost equal number that are or will be extinct.
Pharmaceutical and chemical residues in water deform and shorten lifespans; long-term effects are unknown.
Climate warming leads to increased incidence of a fungus which decimates certain frog populations.
It is unknown how the food chain will be affected in those areas where frogs completely disappear.
Establishing protected sanctuaries for frog species may be a solution.
