Speculation grew on who poisoned Victor Yushchenko.
Suspects include Vladimir Putin or the Russian mafia hired by Putin or Ukrainian officials to keep the Ukraine within the Russian sphere.
Even Yushchenko's inner circle was mentioned.
The poison was firmly identified as tetra-chloro-dibanzo-dioxin, which typically takes from 3 to 14 days for symptoms to appear, raising the question when and where the poisoning actually occurred.
This poison will disfigure and sicken a victim, but not kill quickly.
A parliamentary commission investigation was begun, but Yushchenko refused to cooperate.
He expects to win the run-off election and then conduct a full investigation.
