Theories abound on who poisoned Yushchenko, when, where and why.
Both Russian and Ukranian authorities vehemently deny involvement.
Toxicologists say dioxin was a poor choice if the aim was to kill though it can sicken and disfigure, which it has done.
Also, it takes days or weeks to act.
Yushchenko said he is not accusing Smeshko or his secret services and recently suggested the dioxin may have come from outside the country.
Investigators say Yushchenko is not cooperating though he met the newly assigned prosecutor and pledged to cooperate after the December 26 election.
