Britain's Sudan I red dye food recall has affected products found in 12 provinces and municipalities across China.
Products made by US Heinz Company's China subsidiary were recalled after having been found to contain the dye.
Sudan I was found in products sold by US Kentucky Fried Chicken (KFC) outlets in China.
KFC has stopped selling and will destroy all Sudan I-tainted chicken wings, chicken hamburgers, and sauces.
Another US company, fast food giant McDonald's recalled products in England found to contain the offending dye.
