The waves of the tsunami in southeast Asia wreaked tremendous damage on coral reefs, but much more damage occurred when the waves receded, carrying hazardous chemicals, sludge which smothers the reefs, and debris including cars, refrigerators, even tin roofs, which grind away at the reefs with each successive wave.
India's remote Andaman and Nicobar islands, home to some 200 coral species, suffered extensive damage.
Thailand has closed all marine national parks and is working with UN support and volunteer divers to clean up its southern coast before the monsoons.
France is working to protect coral reefs in the South Pacific.
