Robert Blake, known for his Baretta role on TV, was acquitted of charges he had murdered his wife (described as a con-artist) after the jury had deliberated for nine days in a Van Nuys courthouse.
The jury also found him not guilty of soliciting someone to kill his wife but deadlocked 11-1 on a second solicitation count which Judge Schempp then dismissed.
Jurors said they were concerned with flimsy circumstantial evidence and did not believe the stuntmen, admitted drug users, Blake supposedly solicited to kill his wife.
