Two weeks after Hariri's assassination, Parliament met in a special session which ended suddenly with Karami announcing his government's resignation.
Ten days later, President Lahoud reappointed pro-Syrian Karami as premier.
In late March, some members of Parliament asked the Arab Summit to support an international investigation and the UN for assistance.
A UN report criticized Lebanon authorities' commitment to an investigation.
Political turbulence continued with four bombings in Beirut since March 19.
In April, Hariri's family announced that the second eldest son would assume the political mantle of his slain father, possibly a first step in running for parliamentary election.
