Parkinson's disease starts in middle to late life.
Symptoms occur when 80%of dopamine producing cells die and can include loss of balance.
Recent research has found a flaw in the LRRK2 gene may cause 4% of the cases.
Other causes are suspected environmental, such as exposure to chemicals and radiation.
Many nations are involved with stem cell research and Parkinson's.
Tobacco may provide some protection.
In trials, GDNF from Amgen Company showed some success.
The success was attributed to the placebo effect and Amgen stopped testing the drug.
Trials have found deep brain stimulation may help alleviate symptoms.
