So far, Chesapeake Bay cleanup efforts have been ineffective.
The scientific study and political debate over the introduction of Asian oysters to bay continue.
Meanwhile, the bay's oysters are nearly gone, crabs are at an all-time low, and there is a massive oxygen-starved dead zone in the bay.
Livestock waste, improperly-treated human waste, farm and lawn fertilizers, construction site run-off, and nitrogen air pollution from power plants and automobiles all contribute to the bay's problems.
Maryland announced a $19.4 million plan to clean up and restore grasses and oyster habitat in the Corsica River, a tributary to the bay's watershed.
