With the market demise of Vioxx, intense competition developed for the lucrative arthritis pain medication market.
Twenty million Americans took Vioxx, accounting for 11% of Merck's sales.
Merck released findings on Arcoxia, a cox-2 drug not approved for sale in the U.S. but available in 48 nations.
Pfizer increased advertising for its cox-2 drugs.
Over the counter pain medications advertised their safety.
Under Congressional scrutiny, the FDA is changing procedures to elevate attention to and action on drug safety.
Both Merck and FDA have contested criticisms on their actions related to Vioxx.
