A regional telecom network is helping to manage the endangered Great Panda and share information about it.
Researchers at China's Wolong panda reserve can process panda data in real time, all day, and in all corners of the park.
Other activities to protect the panda include the suspension of industrial expansion.
Over 150 pandas are in captive breeding programs worldwide.
Panda fertility is low, and offspring in zoos outside China must be returned to China when they mature, according to loan agreements.
The panda is a CITES (Convention on International Trade in Endangered Species) protected animal; strict import-export laws apply.
