The grand jury hearing testimony and reviewing evidence related to the murder of JonBenet Ramsey, was granted an extension to mid-October 1999.
Under State law, grand jury proceedings are secret but media speculation says evidence points to either a family member or an intruder having committed the murder.
The grand jury didn't meet for more than 3 months while detectives conducted additional investigations.
The grand jury can issue indictments, choose not to indict, write an opinion report, or simply adjourn.
Depending on the outcome, the DA can pursue any jury recommendation or empanel another group to start anew.
