Columbine students resumed studies at a neighboring high school on Monday 3 May under heavy security.
Several friends of the gunmen were cautioned not to return to school.
Columbine High School remains a cordoned-off crime scene and is not expected to reopen until fall.
Police believe that the gunmen acted alone but have arrested a man for supplying a handgun to a minor.
One gunman's parents have cooperated with the police; the others have refused unless they are granted immunity.
President Clinton has called a White House strategy session on youth violence.
Congress has scheduled hearings on the same.
