A recent Merck clinical trial revealed that Vioxx elevated patients' risk of cardiovascular complications, 18 months into the trial.
Documents show that Merck hid or denied previous evidence of such problems since as early as 2000.
Nonetheless, Merck maintains it was vigilant in monitoring and disclosing information about the safety of Vioxx and disagrees with reports to the contrary.
Merck's withdrawal of Vioxx caused its third quarter profits to fall 29%.
Responding to criticism that it should have acted sooner, the FDA announced that it would strengthen its system for reviewing the safety of drugs already on the market.
