Female giant pandas have a very short fertile period.
Natural insemination in captivity is rare and, even with artificial insemination, births are rare and cubs are fragile.
The Washington National and San Diego Zoos have had some success.
China continues to pursue the World Natural Heritage site designation and closed mines and other polluters is the site area.
China, France and the US are creating a giant panda museum in southwestern China.
China also offered two pandas to Taiwan.
China is beginning to use mobile technology at panda reserves and is using advanced surgical techniques to save injured pandas.
