The death toll from the Papua New Guinea tsunami is now 705 and could reach 3,000.
About 2500 people have been found alive and some 5000 are still unaccounted for.
Food, water, fuel, sanitation equipment, and medical supplies have begun to arrive Most of the aid is coming from Australia.
Australia has also sent 94 relief workers, including 60 people in medical roles and has set up a field hospital in the area.
Relief efforts face innumerable problems because the mountainous area is extremely remote and is covered with thick jungle.
