Philippine officials confirmed the hostages kidnapped from the Malaysian island Sipadan were being held somewhere on the Philippine island of Sulu by the Abu Sayyaf group, who was demanding a $2.4 million ransom.
The Philippine Government was negotiating for their release, refusing a rebel demand for direct negotiations with the captives' countries.
The military sealed off the area to prevent escape of the 50-70 rebels holding them.
According to a doctor and journalists allowed to see them, the hostages were suffering from hunger, thirst, and diarrhea.
To prevent similar incidents, Philippine and Malaysian militaries intensified joint patrols of the area.
