Isolated cases of mad cow disease continue to appear in Europe and North America.
A French goat was diagnosed with mad cow in 2002, the first known transference to a different specie.
The first death in Japan from Creutzfeldt-Jakob disease occurred in February 2004.
One gene may protect some people from this disease or create different symptoms according to researchers at University College, London.
The U.S. plans to spend $2 million on research into the disease.
Japan is testing all cattle in the nation.
