Eight days after the abduction, rebels allowed a doctor and several journalists to visit the hostages, held on a southwest Philippine island by 50 or more gunmen.
Government soldiers have sealed off the area.
The doctor brought medicine, food, and clothes to the 21 hostages suffering from hunger, diarrhea, and thirst.
Eleven boxes of supplies were provided by the French, German, and Finnish embassies.
The captives' embassies rejected a rebel demand for direct negotiations.
The rebels are also demanding a multi-million dollar ransom.
Officials do not think that this abduction is related to an earlier abduction of 27 hostages.
