In the Bahamas, hurricane Floyd's 140 mph winds uprooted trees, toppled power lines, stripped roofs off homes and flooded streets.
Several people were treated for minor injuries.
Vacationers sought shelter inside secure hotel lobbies.
The storm interrupted airline flights, cruises and shipping traffic between the US and the Caribbean.
In the US, the president issued a disaster declaration, enabling FEMA to begin supporting state and local authorities.
The National Guard was activated in Florida, Georgia, and both Carolinas.
Walt Disney World closed for the first time ever because of weather and military sent aircraft inland and ships out of port.
