Psychiatric, long-term treatment has been the standard for eating disorders.
New research questions environmental causes (i.e.
a "thin" culture), finding drugs may eliminate the compulsive nature of some disorders, and that genetic causes may be treatable.
Traditional therapies exclude parents and prohibit controlled feeding, both ignored by the parents of an anorexic whom they successfully treated.
A documentary shows that eating disorders are little understood and poorly treated with traditional therapies.
Greater numbers of binge-eaters are joining support groups.
Web sites glamorizing anorexic and bulimic behavior and lifestyle are harmful.
Yahoo has blocked these at the request of concerned organizations.
