A study of twins shows a genetic factor in eating disorders is highly likely; identifying the genes may lead to prevention and treatment.
Anorexia has high relapse rates and few medications.
Some scientists are treating it as a phobia, and are testing the TB drug D-cycloserine, which affects learning, so patients can unlearn their negative perceptions of food.
Scientists find overactivity in dopamine receptors in the brains of recovered anorexics.
Dopamine is a pleasure-regulator.
Since binge-eating is like an addiction, "Anonymous" groups like AA have been formed.
It takes an average of 7 years to recover from an eating disorder.
