The U.S. will spend $2 million on research with Britain, Italy, and Spain.
This is in addition to the $4.7 million already allocated.
Meanwhile British researchers have discovered a gene that might make some people more resistant to MCD.
A French goat has become the first known case of MCD in a non-bovine animal.
Japan had its first MCD casualty - a man infected during a stay in Britain.
Japan insists that because of testing all Japanese beef is safe.
Spain, having discovered its 20th infected animal, ordered that all the animals on that farm be slaughtered.
