The preliminary report on the Helios crash shows the jet had a problem in the pressurization system that incapacitated its two pilots.
A crew member with pilot training attempted in vain to control and land the plane, and the final cause of the crash was that the jet ran out of fuel.
At least 26 people aboard Helios Flight 522 were alive, although not necessarily conscious, when it crashed.
Pilot error is suspected in connection with a cabin pressure alert.
Boeing has issued a message to 737 operators that on hearing a warning horn pilots must check cabin pressure.
