A Marion County Judge refused the Hillsborough County plea bargain against Debra Lafave since one of the sexual contacts she had with the 14-year old victim occurred in Marion County.
The Judge wanted expert reports on a trial's impact on the youth.
On Wednesday, March 8, a psychiatrist testified a trial would harm the boy.
The following Tuesday morning, the judge rejected the plea deal and set a trial date.
That afternoon, prosecutors dropped Marion county charges and the penalties against Lafave remained those in the Hillsborough agreement.
The victim's mother expressed relief that there would be no trial.
