At the end of March, 1999, a month after the deadly Austrian avalanches, the hardest hit resort, Galtuer, reported that 32 ski vacationers and 6 villagers had been killed.
At least two deaths had been reported earlier in the town of Valzur.
Few ski tourists came to the resort in March, usually their busiest time.
The avalanches were considered the most dangerous in 400 years, with speeds of nearly 200 kilometers per hour.
