A government delegation went to Baluchistan on Tuesday 22 March to try to end a siege of the Dera Bugti military base by hundreds of heavily armed tribesmen but the standoff continued.
The rebels ended the blockade on 13 April and Pakistani military started removing checkpoints around the town, but tensions remained high.
Rockets hit a military headquarters on 25 March, wounding three soldiers, and the following Tuesday a land mine exploded under a jeep, seriously injuring four soldiers.
In late April armed commandos were sent to guard trains and railroad stations in Baluchistan after railroad tracks had been bombed.
