The US attack on Khartoum has been condemned by the Arab League, Jordan, Yemen, and Iran.
Israel, Turkey and Britain have come out in support of the US.
Sudan has denounced the US Administration strongly and recalled its diplomats in Washington.
It has filed complaints with the UN, the Arab League, and other international organizations and urged the UN to undertake an investigation into the attack.
Sudan has also called an emergency meeting of its National Security and Defense Council and opened all training camps to volunteers for the national militia.
The casualty count is one dead, nine wounded.
