Twenty states require helmets for all riders; other states have under-18 rules.
Three years after Arizona's helmet law was repealed they had a peak year for motorcycle deaths.
However, more deaths were attributed to inexperienced older riders than lack of protective gear.
Texas' 8-year-old helmet law was modified to require a safety course or $10,000 insurance policy for helmetless riders.
Some riders claim helmets impair vision and hearing, and protest the imposition of punitive action on those who accept the risk of helmetless riding.
Other activities requiring helmets are baseball and Segway-riding.
