The death toll from the U.S. attack on a Sudanese factory climbed to one although Sudan claimed a large number were killed and injured in the attacks; 5000 were injured in the U.S. embassy bombings being avenged.
The Arab League condemned the U.S. attack and will convene an emergency meeting to discuss it.
It urged the U.S. to refrain from acts jeopardizing world peace and security.
Iran condemned the U.S. action, whilst Egypt, Jordan, and Temen called for caution and dialog to settle problems.
Turkey and Israel expressed support for the U.S. Meanwhile, Sudan's opposition movements took a lower profile.
