Russell Henderson pled guilty to felony murder and kidnapping, avoiding a trial and possible death sentence.
He was sentenced to two consecutive life terms and will be ineligible for parole.
However, Henderson said his co-defendant delivered the fatal blow.
He also alleged McKinney struck him when he tried to stop the beating.
The girlfriends of both defendants were charged with being accessories after the fact to murder.
Henderson's girlfriend pled guilty and is awaiting sentencing.
She had helped hide Henderson's bloody clothing, which had Shepard's blood on it.
Shepard became a symbol of anti-gay violence, inspiring worldwide rallies and vigils.
