A day before his trial was to start, Russell Henderson pleaded guilty to murder, avoiding trial and a possible death sentence.
State district Judge Jeffrey Connell sentenced him to two consecutive life terms without possibility of parole.
Henderson admitted he had tied Shepard to a fence and left him for dead.
Defense attorney Wyatt Skaggs told prospective jurors that Henderson witnessed the beating but didn't participate in it.
Shepard has become a symbol of violence against gay people.
In April, President Clinton will endorse a bill expanding federal hate crime laws to include offenses based on sexual orientation.
