In addition to US food products contaminated with Listeria and E.coli bacteria, other products were also being recalled because the packages did not warn that they contained the possible allergens buttermilk, whey, and genetically engineered corn.
The US Department of Agriculture was unsure if a rise in recalls between 1997 and 1998 for Listeria was because there were more contaminated products or there was better reporting.
The mortality rate for listeriosis is about 30 percent.
There are estimated 10,000-20,000 cases of E.coli infection in the US annually.
E.coli can cause serious illness and sometimes death, especially in children and elderly.
