Motorcyclists continue to protest wearing a helmet and 52% of motorcycly fatalities were not wearing one.
In 2004, only 20 states require this helmet.
More people over 40 are becoming motorcycle riders and fight wearing helmets and getting training as fatalities rise.
Some believe more training of cyclists and truck and auto drivers is the answer.
Some recommend giving children helmets along with recreational toys.
Face guards for youth baseball are also recommended.
