The avalanches in February were declared the most dangerous in 400 years and the ones in Galtuer were the severest in Europe this winter.
The Austrian chancellor and foreign minister visited on February 25 to help coordinate rescue efforts.
The search for survivors ended on February 26, with the death toll set at 38.
By March skiers were returning to other alpine resorts, but business in Galtuer was still off.
