Van Gogh's killer, identified as Mohammed B., was arraigned on charges of murder and terrorism, and will be tried as a terrorist under a new terrorism law.
Four others were charged with terrorist-related activities and a fifth will be charged.
The killer left a note calling for global jihad.
It also threatened the ex-Muslim woman and liberal politician with whom Van Gogh made his movie, as well as the mayor of Amsterdam.
The government has declared war on Islamic extremism, designating extra funds for the intelligence services and evaluating current laws to ease crackdowns on violent radical Muslims.
