A new Air Force report acknowledges evidence linking Agent Orange to cases of diabetes, with a direct relationship between severity of the disease and levels of dioxin in the body.
This is not always the case with other diseases suspected of being caused by dioxin.
Agent Orange may have been tested in Panama prior to deployment in Vietnam, thus affecting many Panamanians and Americans.
There are unconfirmed reports that it was also used in Korea.
Vietnam claims one million victims of Agent orange in his country.
The government will provide monthly allowances for affected citizens and their disabled children.
