In 2000, Vietnam's Vice President said one million Vietnamese suffer Agent Orange effects.
A U.S. admiral had ordered Agent Orange sprayed over where his son was fighting in Vietnam.
This son died of cancer at age 42.
Also in 2000, a $140 million, 25 year, Air Force study linked Agent Orange with adult-onset diabetes and found higher incidences of heart disease and high blood pressure in victims.
The U.S. military sprayed Agent Orange south of the Korean Demilitarized Zone in 1968-1969 and field tested it in Panama during the Vietnam War.
Three U.S. service men died from the Panama spraying.
