The enormous toll from the tsunami in the Indian Ocean serves as a warning about the consequences of damaging the environment.
The mangrove forests took a terrible beating and more than 60,000 acres of mangroves were seriously harmed, but the forests absorbed much of the power of the waves and thus helped to protect the coastline and save lives.
It will take hundreds of millions of dollars and many years to re-grow the mangrove forests, but many countries including China, Indonesia, Malaysia, Myanmar, and Bangladesh are planning to do so.
