Approval to resume full production at the two Statoil platforms was given on January 24.
Statoil reported that the leak occurred when suction drew natural gas into the well where is escaped through a worn casing.
This was attributed to inadequate planning and risk appreciation and failure to observe safety rules.
The safety authority said the incident could have been one of the worst catastrophes on the Norwegian continental shelf.
It concluded the incident was the failure of Statoil's planning, procedures and assessments and demanded improvement.
The police were investigating for criminal negligence.
