Proposals to preserve the Maryland oyster include placing them on the endangered species list.
However since no regional specificity is allowed for invertebrates a resulting ban would be on all oysters, everywhere.
Since oysters are a natural filter against pollution, restoring their numbers would contribute to cleaning Chesapeake waters but this could take decades.
Supporters of introducing the Asian oyster say they grow bigger and faster, and would add the filtering capacity needed.
Such a step is irreversible, however.
No decision has been made.
Genetic altering of native oysters to made them disease-resistant has been proposed.
