There have been massive protests and demonstrations in Beirut following the assassination of Hariri, including four bomb attacks in Beirut in the last two weeks of March.
The pro-Syrian prime minister resigned on 28 February under massive anti-Syrian pressure, but remained temporarily in a caretaker role.
The President reappointed him as prime minister on 10 March.
A UN report said that the investigation into the bombing had not been conducted "in accordance with international standards" and called for an independent international investigation.
Under increasing international pressure, Syria decided to redeploy its troops.
