In the wake of a major tsunami, the United Nations Environment Programme has directed one million dollars towards rehabilitating ecosystems, particularly coral reefs.
The Thai government launched a 4-month campaign to help restore their coral reefs and the diving community is providing outstanding support.
France launched a three-year project to support already-designated protected marine sites and create new protected areas with the goal of sustainable biodiversity amongst Pacific Island coral reefs.
Environmentalists have urged the government of Taiwan to revise its economy-oriented environmental development policy and strategies.
Coral reefs slow down the movement of water, thus providing protection against tsunamis.
