Environmental awareness is rising in China, following the chemical plant explosion on the Songhua River.
Representatives of eight government departments went to Harbin to investigate the pollution caused by the blast.
Active carbon absorbent is being used to purify Harbin's water, with army personnel and civilians working around the clock.
No poisoning cases have yet been reported.
However, it is unclear whether the government's testing and clean-up efforts will extend to the wells in outlying areas.
Across the border, Khabarovsk, Russia, is planning a quick upgrade of their water purification facilities.
Russia lodged complaints that the warnings were too slow.
