The Indonesian death toll from the December earthquake and tsunami rose to 238,982 by February 3.
Temporary shelters are being prepared for 500,000.
Rebuilding costs for the nation could reach $5 billion.
Aceh Province lost 97% of its gross domestic production.
Monthly accounting reports are planned to dispel corruption concerns.
Aid includes a pledge of $73 million from Sweden, which also will freeze Indonesia's $7.6 debt.
Portugal is providing medical teams and Spain is sending vessels and troops.
World-wide $4 billion in aid has been pledged to all nations affected by the tsunami.
