After deliberating for 32.5 hours over nine days, the jury for the Robert Blake trial found him not guilty of murder on March 16.
He also was found not guilty on one count of soliciting for murder.
They deadlocked 11-1 on the second soliciting count.
The judge, Darlene Schempp, later dismissed this charge.
Blake cut off his electronic monitor at a press conference.
His fans partied at Vitello's, the restaurant near where Bakley died.
Her daughter is planning a wrongful death suit.
